apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: signoz-cert
  namespace: istio-system
spec:
  secretName: signoz-cert
  dnsNames:
    - <change-me>
  issuerRef:
    kind: ClusterIssuer
    name: infra-dns-lets-encrypt-cluster-issuer-staging
