apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: infra-keycloak
type: Opaque
stringData:
  KEY_CLOAK_DB_PASSWORD: "<change-me>"
  KEY_CLOAK_ADMIN_PASSWORD: "<change-me>"