apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: istio-system
spec:
  secretName: keycloak-cert
  dnsNames:
    - <change-me>
  issuerRef:
    kind: ClusterIssuer
    name: infra-lets-encrypt-cluster-issuer-staging
